name: Linux

on:
  push:
    paths:
    - "CMakeLists.txt"
    - "Source"
    - "JuceLibraryCode"
    - "PluginGenerator"
    - "Plugins"

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        sudo apt update
        cd Resources/Scripts
        sudo ./install_linux_dependencies.sh
        cd ../../Build && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
    - name: build
      run: |
        cd Build
        make
#    - name: test
#      run: cd build && ctest