name: macOS

on:
  push:

jobs:
  build-osx:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        cd Build 
        cmake -G "Xcode" ..
    - name: build
      run: |
        cd Build 
        xcodebuild -project open-ephys-GUI.xcodeproj -scheme ALL_BUILD -configuration Release 
#    - name: test
#      run: cd build && ctest
    - name: deploy_test
      if: github.ref == 'refs/heads/testing'
      env:
        bintrayUser: ${{ secrets.bintrayUsername }}
        bintrayApiKey: ${{ secrets.bintrayApiKey }}
      run: |
        gui_ver=$(git describe --tags $(git rev-list --tags --max-count=1))
        zipfile=open-ephys-${gui_ver}-mac-beta.zip
        cd Build/Release
        mkdir open-ephys
        mv open-ephys.app/ open-ephys
        cp -r ../../Resources/DataFiles open-ephys/
        cp -r ../../Licenses open-ephys/
        zip -r $zipfile open-ephys
        user_info="$bintrayUser:$bintrayApiKey"
        curl -T $zipfile --user $user_info https://api.bintray.com/content/open-ephys-gui/Test/Test-mac/$gui_ver/$zipfile
        curl -X POST --user $user_info https://api.bintray.com/content/open-ephys-gui/Test/Test-mac/$gui_ver/publish
        brew install create-dmg && create-dmg \
          --volname "Open-Ephys Installer" \
          --volicon "open-ephys/open-ephys.app/Contents/Resources/Icon.icns" \
          --background "open-ephys/open-ephys.app/Contents/Resources/dmg_background.png" \
          --window-pos 300 0 \
          --window-size 688 416 \
          --icon-size 128 \
          --icon "open-ephys.app" 200 190 \
          --hide-extension "Open-Ephys.app" \
          --app-drop-link 500 188 \
          "Open-Ephys-Installer.dmg" \
          "open-ephys/"
        user_info="$bintrayUser:$bintrayApiKey"
        curl -T Open-Ephys-Installer.dmg --user $user_info https://api.bintray.com/content/open-ephys-gui/Test-Installer/Test-Installer-Mac/$gui_ver/Open-Ephys-Installer.dmg
        curl -X POST --user $user_info https://api.bintray.com/content/open-ephys-gui/Test-Installer/Test-Installer-Mac/$gui_ver/publish
    - name: deploy_release
      if: github.ref == 'refs/heads/master'
      env:
        bintrayUser: ${{ secrets.bintrayUsername }}
        bintrayApiKey: ${{ secrets.bintrayApiKey }}
      run: |
        gui_ver=$(git describe --tags $(git rev-list --tags --max-count=1))
        zipfile=open-ephys-${gui_ver}-mac.zip
        cd Build/Release
        mkdir open-ephys
        mv open-ephys.app/ open-ephys
        cp -r ../../Resources/DataFiles open-ephys/
        cp -r ../../Licenses open-ephys/
        zip -r $zipfile open-ephys
        user_info="$bintrayUser:$bintrayApiKey"
        curl -T $zipfile --user $user_info https://api.bintray.com/content/open-ephys-gui/Release/Release-mac/$gui_ver/$zipfile
        curl -X POST --user $user_info https://api.bintray.com/content/open-ephys-gui/Release/Release-mac/$gui_ver/publish
        brew install create-dmg && create-dmg \
          --volname "Open-Ephys Installer" \
          --volicon "open-ephys/open-ephys.app/Contents/Resources/Icon.icns" \
          --background "open-ephys/open-ephys.app/Contents/Resources/dmg_background.png" \
          --window-pos 300 0 \
          --window-size 688 416 \
          --icon-size 128 \
          --icon "open-ephys.app" 200 190 \
          --hide-extension "Open-Ephys.app" \
          --app-drop-link 500 188 \
          "Open-Ephys-Installer.dmg" \
          "open-ephys/"
        user_info="$bintrayUser:$bintrayApiKey"
        curl -T Open-Ephys-Installer.dmg --user $user_info https://api.bintray.com/content/open-ephys-gui/Release-Installer/Release-Installer-Mac/$gui_ver/Open-Ephys-Installer.dmg
        curl -X POST --user $user_info https://api.bintray.com/content/open-ephys-gui/Release-Installer/Release-Installer-Mac/$gui_ver/publish
